<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Product">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="ProductName" type="xsd:string"/><!--Um nome necessita ser uma string-->
                <xsd:element name="ProductType" type="xsd:string"/><!--Type deveria ser uma lista entre tipos, em que apenas aquela seleção de strings seria permitida. Mas por falta desta opção decidi colocar como string.-->
                <xsd:element name="Price" type="xsd:float"/>
                <xsd:element name="Class" type="xsd:string"/>
                <xsd:element name="Company" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="ProductID" type="xsd:positiveInteger" use="required"/>
            <xsd:attribute name="Category" type="xsd:string" use="required"/>
        </xsd:complexType> 
    </xsd:element>
</xsd:schema>